import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
    return [
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 1,
            url: 'https://seasafari.lt/lt',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/baltijos-jura',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/nida',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/minges-kaimas',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/juodkrante',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/privatus-vakareliai',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/lt/vandens-taksi',
        },
        {
            changeFrequency: 'weekly',
            lastModified: new Date(),
            priority: 0.5,
            url: 'https://www.seasafari.lt/lt/blogs',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 1,
            url: 'https://seasafari.lt/en',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/baltijos-jura',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/nida',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/minges-kaimas',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/juodkrante',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/privatus-vakareliai',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/vandens-taksi',
        },
        {
            changeFrequency: 'weekly',
            lastModified: new Date(),
            priority: 0.5,
            url: 'https://www.seasafari.lt/en/blogs',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/baltijos-jura',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/nida',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/minges-kaimas',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/juodkrante',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/privatus-vakareliai',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/en/vandens-taksi',
        },
        {
            changeFrequency: 'weekly',
            lastModified: new Date(),
            priority: 0.5,
            url: 'https://www.seasafari.lt/en/blogs',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 1,
            url: 'https://seasafari.lt/ru',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/baltijos-jura',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/nida',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/minges-kaimas',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/juodkrante',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/privatus-vakareliai',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/vandens-taksi',
        },
        {
            changeFrequency: 'weekly',
            lastModified: new Date(),
            priority: 0.5,
            url: 'https://www.seasafari.lt/ru/blogs',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/baltijos-jura',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/nida',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/minges-kaimas',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/juodkrante',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/privatus-vakareliai',
        },
        {
            changeFrequency: 'monthly',
            lastModified: new Date(),
            priority: 0.8,
            url: 'https://www.seasafari.lt/ru/vandens-taksi',
        },
        {
            changeFrequency: 'weekly',
            lastModified: new Date(),
            priority: 0.5,
            url: 'https://www.seasafari.lt/ru/blogs',
        },
    ]
}